import { node } from "./plan-node-factory"
import { parallelResearchStage, parallelVerificationStage, researcher } from "./plan-stages"
import {
  CoordinatorPlan,
  type CoordinatorPlan as CoordinatorPlanType,
  type IntentProfile as IntentProfileType,
} from "./schema"

export function basePlanForIntent(intent: IntentProfileType): CoordinatorPlanType {
  const goal = intent.goal
  const researchStage = parallelResearchStage(goal)
  const researchDependsOn = ["research_synthesis"]
  return CoordinatorPlan.parse({
    goal,
    nodes:
      intent.workflow === "coding"
        ? [
            ...researchStage,
            node({
              id: "implement",
              description: "Implement change",
              prompt: `Implement the requested change using the research_synthesis handoff as the primary project context.\n\nGoal: ${goal}`,
              task_kind: "implement",
              subagent_type: "general",
              role: "implementer",
              risk: intent.risk_level,
              depends_on: researchDependsOn,
              write_scope: [],
              read_scope: [],
              acceptance_checks: ["Requested change implemented"],
              output_schema: "implementation",
              requires_user_input: false,
              priority: "high",
            }),
            ...parallelVerificationStage(goal, ["implement"]),
            node({
              id: "review",
              description: "Review result",
              prompt: `Independently review the result using research_synthesis and all verifier evidence. Judge conflicts explicitly.\n\nGoal: ${goal}`,
              task_kind: "verify",
              subagent_type: "general",
              role: "reviewer",
              risk: "low",
              depends_on: ["verify_typecheck", "verify_focused_tests", "verify_acceptance"],
              write_scope: [],
              read_scope: [],
              acceptance_checks: ["Review completed"],
              output_schema: "review",
              requires_user_input: false,
            }),
          ]
        : intent.workflow === "debugging"
          ? [
              ...researchStage,
              node({
                id: "debug",
                description: "Diagnose failure",
                prompt: `Diagnose the failure and propose the smallest fix path.\n\nGoal: ${goal}`,
                task_kind: "research",
                subagent_type: "general",
                role: "debugger",
                risk: "medium",
                depends_on: researchDependsOn,
                write_scope: [],
                read_scope: [],
                acceptance_checks: ["Root cause identified"],
                output_schema: "debug",
                requires_user_input: false,
                priority: "high",
              }),
              node({
                id: "implement",
                description: "Apply minimal fix",
                prompt: `Apply the smallest safe fix for the diagnosed issue.\n\nGoal: ${goal}`,
                task_kind: "implement",
                subagent_type: "general",
                role: "implementer",
                risk: intent.risk_level,
                depends_on: ["debug"],
                write_scope: [],
                read_scope: [],
                acceptance_checks: ["Fix applied"],
                output_schema: "implementation",
                requires_user_input: false,
                priority: "high",
              }),
              ...parallelVerificationStage(goal, ["implement"]),
              node({
                id: "review",
                description: "Review fix",
                prompt: `Review the fix using debugger output, research_synthesis, and verifier evidence.\n\nGoal: ${goal}`,
                task_kind: "verify",
                subagent_type: "general",
                role: "reviewer",
                risk: "low",
                depends_on: ["verify_typecheck", "verify_focused_tests", "verify_acceptance"],
                write_scope: [],
                read_scope: [],
                acceptance_checks: ["Fix reviewed"],
                output_schema: "review",
                requires_user_input: false,
              }),
            ]
          : intent.workflow === "review"
            ? [
                researcher(goal),
                node({
                  id: "review",
                  description: "Review work",
                  prompt: `Review the requested target and return prioritized findings only when they are actionable.\n\nGoal: ${goal}`,
                  task_kind: "verify",
                  subagent_type: "general",
                  role: "reviewer",
                  risk: "low",
                  depends_on: ["research"],
                  write_scope: [],
                  read_scope: [],
                  acceptance_checks: ["Review findings are grounded in evidence"],
                  output_schema: "review",
                  requires_user_input: false,
                  priority: "high",
                }),
              ]
            : intent.workflow === "research"
              ? [
                  ...researchStage,
                  node({
                    id: "synthesize",
                    description: "Synthesize research",
                    prompt: `Synthesize research_synthesis into actionable conclusions.\n\nGoal: ${goal}`,
                    task_kind: "generic",
                    subagent_type: "general",
                    role: "writer",
                    risk: "low",
                    depends_on: researchDependsOn,
                    write_scope: [],
                    read_scope: [],
                    acceptance_checks: ["Research report produced"],
                    output_schema: "document",
                    requires_user_input: false,
                  }),
                  node({
                    id: "review",
                    description: "Review synthesis",
                    prompt: `Review the synthesis for unsupported claims and missing caveats.\n\nGoal: ${goal}`,
                    task_kind: "verify",
                    subagent_type: "general",
                    role: "reviewer",
                    risk: "low",
                    depends_on: ["synthesize"],
                    write_scope: [],
                    read_scope: [],
                    acceptance_checks: ["Synthesis reviewed"],
                    output_schema: "review",
                    requires_user_input: false,
                  }),
                ]
              : intent.workflow === "environment-audit"
                ? [
                    node({
                      id: "audit",
                      description: "Audit environment",
                      prompt: `Inspect the local environment, dependency state, and toolchain blockers.\n\nGoal: ${goal}`,
                      task_kind: "research",
                      subagent_type: "general",
                      role: "environment-auditor",
                      risk: intent.risk_level,
                      depends_on: [],
                      write_scope: [],
                      read_scope: [],
                      acceptance_checks: ["Environment blockers identified"],
                      output_schema: "environment-diagnosis",
                      requires_user_input: false,
                      priority: "high",
                    }),
                    node({
                      id: "verify",
                      description: "Verify environment findings",
                      prompt: `Verify the audit findings with concrete checks where possible.\n\nGoal: ${goal}`,
                      task_kind: "verify",
                      subagent_type: "general",
                      role: "verifier",
                      risk: "low",
                      depends_on: ["audit"],
                      write_scope: [],
                      read_scope: [],
                      acceptance_checks: ["Findings verified"],
                      output_schema: "verification",
                      requires_user_input: false,
                    }),
                    node({
                      id: "report",
                      description: "Write environment report",
                      prompt: `Write a concise environment diagnosis with blockers and next actions.\n\nGoal: ${goal}`,
                      task_kind: "generic",
                      subagent_type: "general",
                      role: "writer",
                      risk: "low",
                      depends_on: ["verify"],
                      write_scope: [],
                      read_scope: [],
                      acceptance_checks: ["Diagnosis report produced"],
                      output_schema: "document",
                      requires_user_input: false,
                    }),
                  ]
                : intent.workflow === "writing"
                  ? [
                      node({
                        id: "outline",
                        description: "Plan writing structure",
                        prompt: `Create a concise outline with audience, purpose, claims, and constraints.\n\nGoal: ${goal}`,
                        task_kind: "research",
                        subagent_type: "general",
                        role: "planner",
                        risk: "low",
                        depends_on: [],
                        write_scope: [],
                        read_scope: [],
                        acceptance_checks: ["Audience and structure identified"],
                        output_schema: "outline",
                        requires_user_input: false,
                        priority: "high",
                      }),
                      node({
                        id: "draft",
                        description: "Write draft",
                        prompt: `Write the requested artifact from the outline. Preserve caveats and user constraints.\n\nGoal: ${goal}`,
                        task_kind: "generic",
                        subagent_type: "general",
                        role: "writer",
                        risk: intent.risk_level,
                        depends_on: ["outline"],
                        write_scope: [],
                        read_scope: [],
                        acceptance_checks: ["Draft produced"],
                        output_schema: "draft",
                        requires_user_input: false,
                      }),
                      node({
                        id: "style_review",
                        description: "Review style and factuality",
                        prompt: `Review the draft for style fit, unsupported claims, and missing caveats.\n\nGoal: ${goal}`,
                        task_kind: "verify",
                        subagent_type: "general",
                        role: "style-editor",
                        risk: "low",
                        depends_on: ["draft"],
                        write_scope: [],
                        read_scope: [],
                        acceptance_checks: ["Style and factuality reviewed"],
                        output_schema: "review",
                        requires_user_input: false,
                      }),
                    ]
                  : intent.workflow === "data-analysis"
                    ? [
                        node({
                          id: "profile_data",
                          description: "Profile data shape",
                          prompt: `Inspect the available data shape, schema, quality limits, and analysis constraints.\n\nGoal: ${goal}`,
                          task_kind: "research",
                          subagent_type: "general",
                          role: "analyst",
                          risk: "low",
                          depends_on: [],
                          write_scope: [],
                          read_scope: [],
                          acceptance_checks: ["Data schema and limits profiled"],
                          output_schema: "analysis",
                          requires_user_input: false,
                          priority: "high",
                        }),
                        node({
                          id: "analyze_data",
                          description: "Analyze data",
                          prompt: `Run the requested analysis using the profiled constraints and report caveats.\n\nGoal: ${goal}`,
                          task_kind: "generic",
                          subagent_type: "general",
                          role: "analyst",
                          risk: intent.risk_level,
                          depends_on: ["profile_data"],
                          write_scope: [],
                          read_scope: [],
                          acceptance_checks: ["Analysis completed with caveats"],
                          output_schema: "analysis",
                          requires_user_input: false,
                        }),
                        node({
                          id: "verify_stats",
                          description: "Verify statistics and anomalies",
                          prompt: `Verify calculations, statistical assumptions, anomaly handling, and unsupported conclusions.\n\nGoal: ${goal}`,
                          task_kind: "verify",
                          subagent_type: "general",
                          role: "verifier",
                          risk: "low",
                          depends_on: ["analyze_data"],
                          write_scope: [],
                          read_scope: [],
                          acceptance_checks: ["Statistics and anomalies verified"],
                          output_schema: "verification",
                          requires_user_input: false,
                        }),
                      ]
                    : intent.workflow === "planning"
                      ? [
                          node({
                            id: "decompose_goal",
                            description: "Decompose goal",
                            prompt: `Break down the goal into milestones, dependencies, risks, and decision points.\n\nGoal: ${goal}`,
                            task_kind: "generic",
                            subagent_type: "general",
                            role: "planner",
                            risk: "low",
                            depends_on: [],
                            write_scope: [],
                            read_scope: [],
                            acceptance_checks: ["Goal decomposed into actionable plan"],
                            output_schema: "plan",
                            requires_user_input: false,
                            priority: "high",
                          }),
                          node({
                            id: "check_constraints",
                            description: "Check constraints and alternatives",
                            prompt: `Check constraints, assumptions, alternatives, and failure modes in the plan.\n\nGoal: ${goal}`,
                            task_kind: "verify",
                            subagent_type: "general",
                            role: "constraint-checker",
                            risk: "low",
                            depends_on: ["decompose_goal"],
                            write_scope: [],
                            read_scope: [],
                            acceptance_checks: ["Constraints and alternatives checked"],
                            output_schema: "review",
                            requires_user_input: false,
                          }),
                          node({
                            id: "risk_review",
                            description: "Review plan risks",
                            prompt: `Review the plan for risk, sequencing, missing owners, and unclear acceptance criteria.\n\nGoal: ${goal}`,
                            task_kind: "verify",
                            subagent_type: "general",
                            role: "risk-reviewer",
                            risk: "low",
                            depends_on: ["check_constraints"],
                            write_scope: [],
                            read_scope: [],
                            acceptance_checks: ["Plan risks reviewed"],
                            output_schema: "review",
                            requires_user_input: false,
                          }),
                        ]
                      : intent.workflow === "personal-admin"
                        ? [
                            node({
                              id: "classify_inbox",
                              description: "Classify personal admin work",
                              prompt: `Classify the requested personal admin work into actions, priorities, and privacy constraints.\n\nGoal: ${goal}`,
                              task_kind: "research",
                              subagent_type: "general",
                              role: "inbox-classifier",
                              risk: "low",
                              depends_on: [],
                              write_scope: [],
                              read_scope: [],
                              acceptance_checks: ["Admin work classified"],
                              output_schema: "summary",
                              requires_user_input: false,
                              priority: "high",
                            }),
                            node({
                              id: "schedule_actions",
                              description: "Prioritize and schedule actions",
                              prompt: `Prioritize the actions and propose a safe schedule with follow-up points.\n\nGoal: ${goal}`,
                              task_kind: "generic",
                              subagent_type: "general",
                              role: "scheduler",
                              risk: intent.risk_level,
                              depends_on: ["classify_inbox"],
                              write_scope: [],
                              read_scope: [],
                              acceptance_checks: ["Actions prioritized and scheduled"],
                              output_schema: "plan",
                              requires_user_input: false,
                            }),
                            node({
                              id: "privacy_review",
                              description: "Review privacy risk",
                              prompt: `Review the proposed personal admin actions for privacy, overreach, and missing user approval.\n\nGoal: ${goal}`,
                              task_kind: "verify",
                              subagent_type: "general",
                              role: "privacy-reviewer",
                              risk: "low",
                              depends_on: ["schedule_actions"],
                              write_scope: [],
                              read_scope: [],
                              acceptance_checks: ["Privacy risk reviewed"],
                              output_schema: "review",
                              requires_user_input: false,
                            }),
                          ]
                        : intent.workflow === "documentation"
                          ? [
                              researcher(goal),
                              node({
                                id: "write",
                                description: "Write documentation",
                                prompt: `Write or update the requested documentation.\n\nGoal: ${goal}`,
                                task_kind: "implement",
                                subagent_type: "general",
                                role: "writer",
                                risk: intent.risk_level,
                                depends_on: ["research"],
                                write_scope: [],
                                read_scope: [],
                                acceptance_checks: ["Documentation produced"],
                                output_schema: "document",
                                requires_user_input: false,
                              }),
                              node({
                                id: "review",
                                description: "Review documentation",
                                prompt: `Review the documentation for accuracy and missing caveats.\n\nGoal: ${goal}`,
                                task_kind: "verify",
                                subagent_type: "general",
                                role: "reviewer",
                                risk: "low",
                                depends_on: ["write"],
                                write_scope: [],
                                read_scope: [],
                                acceptance_checks: ["Documentation reviewed"],
                                output_schema: "review",
                                requires_user_input: false,
                              }),
                            ]
                          : intent.workflow === "automation"
                            ? [
                                researcher(goal),
                                node({
                                  id: "automation_plan",
                                  description: "Plan automation",
                                  prompt: `Turn the repeatable work into an automation plan with trigger, scope, and safety checks.\n\nGoal: ${goal}`,
                                  task_kind: "generic",
                                  subagent_type: "general",
                                  role: "automation-planner",
                                  risk: intent.risk_level,
                                  depends_on: ["research"],
                                  write_scope: [],
                                  read_scope: [],
                                  acceptance_checks: ["Automation plan produced"],
                                  output_schema: "automation-plan",
                                  requires_user_input: intent.risk_level === "high",
                                }),
                                node({
                                  id: "verify",
                                  description: "Verify automation plan",
                                  prompt: `Verify the automation plan for safety, permissions, and failure modes.\n\nGoal: ${goal}`,
                                  task_kind: "verify",
                                  subagent_type: "general",
                                  role: "verifier",
                                  risk: "low",
                                  depends_on: ["automation_plan"],
                                  write_scope: [],
                                  read_scope: [],
                                  acceptance_checks: ["Automation safety reviewed"],
                                  output_schema: "verification",
                                  requires_user_input: false,
                                }),
                              ]
                            : [
                                researcher(goal),
                                node({
                                  id: "execute",
                                  description: "Execute general task",
                                  prompt: `Complete the requested work and produce the expected output.\n\nGoal: ${goal}`,
                                  task_kind: "generic",
                                  subagent_type: "general",
                                  role: intent.workflow === "file-data-organization" ? "implementer" : "writer",
                                  risk: intent.risk_level,
                                  depends_on: ["research"],
                                  write_scope: [],
                                  read_scope: [],
                                  acceptance_checks: ["Requested work completed"],
                                  output_schema: "summary",
                                  requires_user_input: intent.risk_level === "high",
                                }),
                                node({
                                  id: "review",
                                  description: "Review result",
                                  prompt: `Review the result against the goal and report residual risks.\n\nGoal: ${goal}`,
                                  task_kind: "verify",
                                  subagent_type: "general",
                                  role: "reviewer",
                                  risk: "low",
                                  depends_on: ["execute"],
                                  write_scope: [],
                                  read_scope: [],
                                  acceptance_checks: ["Result reviewed"],
                                  output_schema: "review",
                                  requires_user_input: false,
                                }),
                              ],
  })
}
