import { Config } from "effect"

function env(key: string) {
  return process.env[`OPENAGT_${key}`] ?? process.env[`OPENCODE_${key}`]
}

function truthy(key: string) {
  const value =
    process.env[key]?.toLowerCase() ??
    env(key.replace(/^OPENAGT_/, "").replace(/^OPENCODE_/, ""))?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value =
    process.env[key]?.toLowerCase() ??
    env(key.replace(/^OPENAGT_/, "").replace(/^OPENCODE_/, ""))?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key] ?? env(key.replace(/^OPENAGT_/, "").replace(/^OPENCODE_/, ""))
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const OPENAGT_EXPERIMENTAL = truthy("OPENAGT_EXPERIMENTAL")
const OPENAGT_DISABLE_CLAUDE_CODE = truthy("OPENAGT_DISABLE_CLAUDE_CODE")
const OPENAGT_DISABLE_CLAUDE_CODE_SKILLS =
  OPENAGT_DISABLE_CLAUDE_CODE || truthy("OPENAGT_DISABLE_CLAUDE_CODE_SKILLS")
const OPENCODE_EXPERIMENTAL = truthy("OPENCODE_EXPERIMENTAL")
const OPENCODE_DISABLE_CLAUDE_CODE = truthy("OPENCODE_DISABLE_CLAUDE_CODE")
const OPENCODE_DISABLE_CLAUDE_CODE_SKILLS =
  OPENCODE_DISABLE_CLAUDE_CODE || truthy("OPENCODE_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["OPENAGT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"] ?? process.env["OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  OPENAGT_AUTO_SHARE: truthy("OPENAGT_AUTO_SHARE"),
  OPENAGT_AUTO_HEAP_SNAPSHOT: truthy("OPENAGT_AUTO_HEAP_SNAPSHOT"),
  OPENAGT_GIT_BASH_PATH: process.env["OPENAGT_GIT_BASH_PATH"] ?? process.env["OPENCODE_GIT_BASH_PATH"],
  OPENAGT_CONFIG: process.env["OPENAGT_CONFIG"] ?? process.env["OPENCODE_CONFIG"],
  OPENAGT_CONFIG_CONTENT: process.env["OPENAGT_CONFIG_CONTENT"] ?? process.env["OPENCODE_CONFIG_CONTENT"],
  OPENAGT_DISABLE_AUTOUPDATE: truthy("OPENAGT_DISABLE_AUTOUPDATE"),
  OPENAGT_ALWAYS_NOTIFY_UPDATE: truthy("OPENAGT_ALWAYS_NOTIFY_UPDATE"),
  OPENAGT_DISABLE_PRUNE: truthy("OPENAGT_DISABLE_PRUNE"),
  OPENAGT_DISABLE_TERMINAL_TITLE: truthy("OPENAGT_DISABLE_TERMINAL_TITLE"),
  OPENAGT_SHOW_TTFD: truthy("OPENAGT_SHOW_TTFD"),
  OPENAGT_PERMISSION: process.env["OPENAGT_PERMISSION"] ?? process.env["OPENCODE_PERMISSION"],
  OPENAGT_DISABLE_DEFAULT_PLUGINS: truthy("OPENAGT_DISABLE_DEFAULT_PLUGINS"),
  OPENAGT_DISABLE_LSP_DOWNLOAD: truthy("OPENAGT_DISABLE_LSP_DOWNLOAD"),
  OPENAGT_ENABLE_EXPERIMENTAL_MODELS: truthy("OPENAGT_ENABLE_EXPERIMENTAL_MODELS"),
  OPENAGT_DISABLE_AUTOCOMPACT: truthy("OPENAGT_DISABLE_AUTOCOMPACT"),
  OPENAGT_DISABLE_MODELS_FETCH: truthy("OPENAGT_DISABLE_MODELS_FETCH"),
  OPENAGT_DISABLE_MOUSE: truthy("OPENAGT_DISABLE_MOUSE"),
  OPENAGT_DISABLE_CLAUDE_CODE,
  OPENAGT_DISABLE_CLAUDE_CODE_PROMPT: OPENAGT_DISABLE_CLAUDE_CODE || truthy("OPENAGT_DISABLE_CLAUDE_CODE_PROMPT"),
  OPENAGT_DISABLE_CLAUDE_CODE_SKILLS,
  OPENAGT_DISABLE_EXTERNAL_SKILLS: OPENAGT_DISABLE_CLAUDE_CODE_SKILLS || truthy("OPENAGT_DISABLE_EXTERNAL_SKILLS"),
  OPENAGT_FAKE_VCS: process.env["OPENAGT_FAKE_VCS"] ?? process.env["OPENCODE_FAKE_VCS"],
  OPENAGT_SERVER_PASSWORD: process.env["OPENAGT_SERVER_PASSWORD"] ?? process.env["OPENCODE_SERVER_PASSWORD"],
  OPENAGT_SERVER_USERNAME: process.env["OPENAGT_SERVER_USERNAME"] ?? process.env["OPENCODE_SERVER_USERNAME"],
  OPENAGT_ENABLE_QUESTION_TOOL: truthy("OPENAGT_ENABLE_QUESTION_TOOL"),

  OPENCODE_AUTO_SHARE: truthy("OPENCODE_AUTO_SHARE"),
  OPENCODE_AUTO_HEAP_SNAPSHOT: truthy("OPENCODE_AUTO_HEAP_SNAPSHOT"),
  OPENCODE_GIT_BASH_PATH: process.env["OPENCODE_GIT_BASH_PATH"] ?? process.env["OPENAGT_GIT_BASH_PATH"],
  OPENCODE_CONFIG: process.env["OPENCODE_CONFIG"] ?? process.env["OPENAGT_CONFIG"],
  OPENCODE_CONFIG_CONTENT: process.env["OPENCODE_CONFIG_CONTENT"] ?? process.env["OPENAGT_CONFIG_CONTENT"],
  OPENCODE_DISABLE_AUTOUPDATE: truthy("OPENCODE_DISABLE_AUTOUPDATE"),
  OPENCODE_ALWAYS_NOTIFY_UPDATE: truthy("OPENCODE_ALWAYS_NOTIFY_UPDATE"),
  OPENCODE_DISABLE_PRUNE: truthy("OPENCODE_DISABLE_PRUNE"),
  OPENCODE_DISABLE_TERMINAL_TITLE: truthy("OPENCODE_DISABLE_TERMINAL_TITLE"),
  OPENCODE_SHOW_TTFD: truthy("OPENCODE_SHOW_TTFD"),
  OPENCODE_PERMISSION: process.env["OPENCODE_PERMISSION"],
  OPENCODE_DISABLE_DEFAULT_PLUGINS: truthy("OPENCODE_DISABLE_DEFAULT_PLUGINS"),
  OPENCODE_DISABLE_LSP_DOWNLOAD: truthy("OPENCODE_DISABLE_LSP_DOWNLOAD"),
  OPENCODE_ENABLE_EXPERIMENTAL_MODELS: truthy("OPENCODE_ENABLE_EXPERIMENTAL_MODELS"),
  OPENCODE_DISABLE_AUTOCOMPACT: truthy("OPENCODE_DISABLE_AUTOCOMPACT"),
  OPENCODE_DISABLE_MODELS_FETCH: truthy("OPENCODE_DISABLE_MODELS_FETCH"),
  OPENCODE_DISABLE_MOUSE: truthy("OPENCODE_DISABLE_MOUSE"),
  OPENCODE_DISABLE_CLAUDE_CODE,
  OPENCODE_DISABLE_CLAUDE_CODE_PROMPT: OPENCODE_DISABLE_CLAUDE_CODE || truthy("OPENCODE_DISABLE_CLAUDE_CODE_PROMPT"),
  OPENCODE_DISABLE_CLAUDE_CODE_SKILLS,
  OPENCODE_DISABLE_EXTERNAL_SKILLS: OPENCODE_DISABLE_CLAUDE_CODE_SKILLS || truthy("OPENCODE_DISABLE_EXTERNAL_SKILLS"),
  OPENCODE_FAKE_VCS: process.env["OPENCODE_FAKE_VCS"],
  OPENCODE_SERVER_PASSWORD: process.env["OPENCODE_SERVER_PASSWORD"] ?? process.env["OPENAGT_SERVER_PASSWORD"],
  OPENCODE_SERVER_USERNAME: process.env["OPENCODE_SERVER_USERNAME"] ?? process.env["OPENAGT_SERVER_USERNAME"],
  OPENCODE_ENABLE_QUESTION_TOOL: truthy("OPENCODE_ENABLE_QUESTION_TOOL"),

  // Experimental
  OPENAGT_EXPERIMENTAL,
  OPENCODE_EXPERIMENTAL,
  OPENAGT_EXPERIMENTAL_FILEWATCHER: Config.boolean("OPENAGT_EXPERIMENTAL_FILEWATCHER")
    .pipe(Config.withDefault(false)),
  OPENCODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("OPENCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENAGT_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("OPENAGT_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENAGT_EXPERIMENTAL_ICON_DISCOVERY: OPENAGT_EXPERIMENTAL || truthy("OPENAGT_EXPERIMENTAL_ICON_DISCOVERY"),
  OPENCODE_EXPERIMENTAL_ICON_DISCOVERY: OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_ICON_DISCOVERY"),
  OPENAGT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("OPENAGT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  OPENAGT_ENABLE_EXA: truthy("OPENAGT_ENABLE_EXA") || OPENAGT_EXPERIMENTAL || truthy("OPENAGT_EXPERIMENTAL_EXA"),
  OPENCODE_ENABLE_EXA: truthy("OPENCODE_ENABLE_EXA") || OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_EXA"),
  OPENAGT_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("OPENAGT_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  OPENAGT_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("OPENAGT_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  OPENAGT_EXPERIMENTAL_OXFMT: OPENAGT_EXPERIMENTAL || truthy("OPENAGT_EXPERIMENTAL_OXFMT"),
  OPENCODE_EXPERIMENTAL_OXFMT: OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_OXFMT"),
  OPENAGT_EXPERIMENTAL_LSP_TY: truthy("OPENAGT_EXPERIMENTAL_LSP_TY"),
  OPENCODE_EXPERIMENTAL_LSP_TY: truthy("OPENCODE_EXPERIMENTAL_LSP_TY"),
  OPENAGT_EXPERIMENTAL_LSP_TOOL: OPENAGT_EXPERIMENTAL || truthy("OPENAGT_EXPERIMENTAL_LSP_TOOL"),
  OPENCODE_EXPERIMENTAL_LSP_TOOL: OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_LSP_TOOL"),
  OPENAGT_EXPERIMENTAL_PLAN_MODE: OPENAGT_EXPERIMENTAL || truthy("OPENAGT_EXPERIMENTAL_PLAN_MODE"),
  OPENCODE_EXPERIMENTAL_PLAN_MODE: OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_PLAN_MODE"),
  OPENAGT_EXPERIMENTAL_MARKDOWN: !falsy("OPENAGT_EXPERIMENTAL_MARKDOWN"),
  OPENCODE_EXPERIMENTAL_MARKDOWN: !falsy("OPENCODE_EXPERIMENTAL_MARKDOWN"),
  OPENAGT_MODELS_URL: process.env["OPENAGT_MODELS_URL"] ?? process.env["OPENCODE_MODELS_URL"],
  OPENAGT_MODELS_PATH: process.env["OPENAGT_MODELS_PATH"] ?? process.env["OPENCODE_MODELS_PATH"],
  OPENCODE_MODELS_URL: process.env["OPENCODE_MODELS_URL"] ?? process.env["OPENAGT_MODELS_URL"],
  OPENCODE_MODELS_PATH: process.env["OPENCODE_MODELS_PATH"] ?? process.env["OPENAGT_MODELS_PATH"],
  OPENAGT_DISABLE_EMBEDDED_WEB_UI: truthy("OPENAGT_DISABLE_EMBEDDED_WEB_UI"),
  OPENCODE_DISABLE_EMBEDDED_WEB_UI: truthy("OPENCODE_DISABLE_EMBEDDED_WEB_UI"),
  OPENAGT_DB: process.env["OPENAGT_DB"] ?? process.env["OPENCODE_DB"],
  OPENCODE_DB: process.env["OPENCODE_DB"] ?? process.env["OPENAGT_DB"],
  OPENAGT_DISABLE_CHANNEL_DB: truthy("OPENAGT_DISABLE_CHANNEL_DB"),
  OPENCODE_DISABLE_CHANNEL_DB: truthy("OPENCODE_DISABLE_CHANNEL_DB"),
  OPENAGT_SKIP_MIGRATIONS: truthy("OPENAGT_SKIP_MIGRATIONS"),
  OPENCODE_SKIP_MIGRATIONS: truthy("OPENCODE_SKIP_MIGRATIONS"),
  OPENAGT_STRICT_CONFIG_DEPS: truthy("OPENAGT_STRICT_CONFIG_DEPS"),
  OPENCODE_STRICT_CONFIG_DEPS: truthy("OPENCODE_STRICT_CONFIG_DEPS"),
  OPENAGT_SANDBOX_SEATBELT_HELPER: process.env["OPENAGT_SANDBOX_SEATBELT_HELPER"] ?? process.env["OPENCODE_SANDBOX_SEATBELT_HELPER"],
  OPENAGT_SANDBOX_WINDOWS_HELPER: process.env["OPENAGT_SANDBOX_WINDOWS_HELPER"] ?? process.env["OPENCODE_SANDBOX_WINDOWS_HELPER"],
  OPENAGT_SANDBOX_LANDLOCK_HELPER: process.env["OPENAGT_SANDBOX_LANDLOCK_HELPER"] ?? process.env["OPENCODE_SANDBOX_LANDLOCK_HELPER"],
  OPENCODE_SANDBOX_SEATBELT_HELPER: process.env["OPENCODE_SANDBOX_SEATBELT_HELPER"] ?? process.env["OPENAGT_SANDBOX_SEATBELT_HELPER"],
  OPENCODE_SANDBOX_WINDOWS_HELPER: process.env["OPENCODE_SANDBOX_WINDOWS_HELPER"] ?? process.env["OPENAGT_SANDBOX_WINDOWS_HELPER"],
  OPENCODE_SANDBOX_LANDLOCK_HELPER: process.env["OPENCODE_SANDBOX_LANDLOCK_HELPER"] ?? process.env["OPENAGT_SANDBOX_LANDLOCK_HELPER"],

  OPENAGT_WORKSPACE_ID: process.env["OPENAGT_WORKSPACE_ID"] ?? process.env["OPENCODE_WORKSPACE_ID"],
  OPENCODE_WORKSPACE_ID: process.env["OPENCODE_WORKSPACE_ID"],
  OPENAGT_EXPERIMENTAL_HTTPAPI: truthy("OPENAGT_EXPERIMENTAL_HTTPAPI"),
  OPENCODE_EXPERIMENTAL_HTTPAPI: truthy("OPENCODE_EXPERIMENTAL_HTTPAPI"),
  OPENAGT_EXPERIMENTAL_WORKSPACES: OPENAGT_EXPERIMENTAL || truthy("OPENAGT_EXPERIMENTAL_WORKSPACES"),
  OPENCODE_EXPERIMENTAL_WORKSPACES: OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get OPENAGT_DISABLE_PROJECT_CONFIG() {
    return truthy("OPENAGT_DISABLE_PROJECT_CONFIG") || truthy("OPENCODE_DISABLE_PROJECT_CONFIG")
  },
  get OPENCODE_DISABLE_PROJECT_CONFIG() {
    return truthy("OPENCODE_DISABLE_PROJECT_CONFIG") || truthy("OPENAGT_DISABLE_PROJECT_CONFIG")
  },
  get OPENAGT_TUI_CONFIG() {
    return process.env["OPENAGT_TUI_CONFIG"] ?? process.env["OPENCODE_TUI_CONFIG"]
  },
  get OPENCODE_TUI_CONFIG() {
    return process.env["OPENCODE_TUI_CONFIG"] ?? process.env["OPENAGT_TUI_CONFIG"]
  },
  get OPENAGT_CONFIG_DIR() {
    return process.env["OPENAGT_CONFIG_DIR"] ?? process.env["OPENCODE_CONFIG_DIR"]
  },
  get OPENCODE_CONFIG_DIR() {
    return process.env["OPENCODE_CONFIG_DIR"] ?? process.env["OPENAGT_CONFIG_DIR"]
  },
  get OPENAGT_PURE() {
    return truthy("OPENAGT_PURE") || truthy("OPENCODE_PURE")
  },
  get OPENCODE_PURE() {
    return truthy("OPENCODE_PURE") || truthy("OPENAGT_PURE")
  },
  get OPENAGT_PLUGIN_META_FILE() {
    return process.env["OPENAGT_PLUGIN_META_FILE"] ?? process.env["OPENCODE_PLUGIN_META_FILE"]
  },
  get OPENCODE_PLUGIN_META_FILE() {
    return process.env["OPENCODE_PLUGIN_META_FILE"] ?? process.env["OPENAGT_PLUGIN_META_FILE"]
  },
  get OPENAGT_CLIENT() {
    return process.env["OPENAGT_CLIENT"] ?? process.env["OPENCODE_CLIENT"] ?? "cli"
  },
  get OPENCODE_CLIENT() {
    return process.env["OPENCODE_CLIENT"] ?? process.env["OPENAGT_CLIENT"] ?? "cli"
  },
}
