// Environment-variable allow/block patterns for shell execution.
// This file does not sanitize env values; EnvSanitizer owns that behavior.

export const BINARY_HIJACK_VARS =
  /^(?:LD_|DYLD_|PATH$|NODE_OPTIONS$|BUN_OPTIONS$|DENO_OPTIONS$|BASH_ENV$|ENV$|PROMPT_COMMAND$|PS4$|IFS$|PYTHONPATH$|PYTHONSTARTUP$|PYTHONHOME$|PERL5OPT$|PERL5LIB$|PERLLIB$|RUBYOPT$|RUBYLIB$|JAVA_TOOL_OPTIONS$|_JAVA_OPTIONS$|GIT_SSH_COMMAND$|GIT_EXEC_PATH$|GIT_DIR$|MAIL$|MAILPATH$)/i

export const SAFE_ENV_VARS = new Set([
  "GOEXPERIMENT",
  "GOOS",
  "GOARCH",
  "CGO_ENABLED",
  "GO111MODULE",
  "RUST_BACKTRACE",
  "RUST_LOG",
  "NODE_ENV",
  "PYTHONUNBUFFERED",
  "PYTHONDONTWRITEBYTECODE",
  "LANG",
  "LANGUAGE",
  "LC_ALL",
  "LC_CTYPE",
  "LC_TIME",
  "CHARSET",
  "TERM",
  "COLORTERM",
  "NO_COLOR",
  "FORCE_COLOR",
  "TZ",
  "LS_COLORS",
  "LSCOLORS",
  "GREP_COLOR",
  "GREP_COLORS",
  "GCC_COLORS",
  "TIME_STYLE",
  "BLOCK_SIZE",
  "BLOCKSIZE",
])

export const ANT_ONLY_SAFE_ENV_VARS = new Set([
  "AWS_PROFILE",
  "CLOUDSDK_CORE_PROJECT",
  "CLUSTER",
  "COO_CLUSTER",
  "COO_CLUSTER_NAME",
  "COO_NAMESPACE",
  "CUDA_VISIBLE_DEVICES",
  "JAX_PLATFORMS",
])
