import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const checkedInSnapshot = path.join(dir, "src/provider/models-snapshot.js")

async function checkedInModelsSnapshot() {
  const prefix = "// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = "
  const text = await Bun.file(checkedInSnapshot).text()
  if (!text.startsWith(prefix)) throw new Error(`Unable to read checked-in models snapshot: ${checkedInSnapshot}`)
  return text.slice(prefix.length)
}

// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : process.env.OPENAGT_USE_CHECKED_IN_MODELS_SNAPSHOT === "1"
    ? await checkedInModelsSnapshot()
    : await fetch(`${modelsUrl}/api.json`)
        .then((x) => x.text())
        .catch(async (error) => {
          if (process.env.OPENAGT_ALLOW_MODELS_SNAPSHOT_FALLBACK !== "1") throw error
          console.warn(`models.dev fetch failed; using checked-in snapshot: ${error}`)
          return checkedInModelsSnapshot()
        })
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")
